In [57]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
import pandas as pd
tf.__version__

'1.14.0'

In [58]:
batch_size = 1

def index_to_char(i):
    return chr(i + 97 if (i != 26) else 32)
def char_to_index(ch):
    return ord(ch) - 97 if (ch != ' ') else 26

text = "hello world"
encoding_size = keras.utils.to_categorical(list(set(map(char_to_index, list(text))))).shape[1]

In [59]:
x_train = [[list(keras.utils.to_categorical(list(map(char_to_index, list(" hello world h")))))]] # ' hello'
y_train = [[list(keras.utils.to_categorical(list(map(char_to_index, list("hello world he")))))]] # 'hello '
print(np.array(x_train).shape)
x_train

(1, 1, 14, 27)


[[[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32),
   array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
   array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
   array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
   array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
   array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
   array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], d

In [ ]:
model = keras.Sequential([
    layers.LSTM(128, input_shape=(None, encoding_size), return_sequences=True),
    layers.Dense(encoding_size, activation='softmax')
])

model.compile(
    optimizer=keras.optimizers.RMSprop(learning_rate=0.02),
    loss=keras.losses.categorical_crossentropy
)

def on_epoch_end(epoch, data):
    if epoch % 10 == 9:
        print("epoch", epoch)
        print("loss", data['loss'])
        
        # Generate text from the initial text ' h'
        text = ' h'
        for i in range(50):
            x = [[list(keras.utils.to_categorical(list(map(char_to_index, list(text)))))]]
            y = model.predict(x)[0][-1]
            text += index_to_char(y.argmax())
        print(text)
        
        
model.fit(
    x_train, 
    y_train, 
    batch_size=batch_size, 
    epochs=500, 
    verbose=False,
    callbacks=[keras.callbacks.LambdaCallback(on_epoch_end=on_epoch_end)]
)

epoch 9
loss 1.6264684200286865
 helllooo hellllllllllllllllllllllllllllllllllllllll
epoch 19
loss 1.3531025648117065
 hello werldrldrdddddddddddddddddddddddddddddddddddd
epoch 29
loss 0.04094976931810379
 hello world helld helld helld helld helld helld hel
epoch 39
loss 0.008073308505117893
 hello world helld helld helld helld helld helld hel
epoch 49
loss 0.0031421410385519266
 hello world helld helld helld helld helld helld hel
epoch 59
loss 0.0013878761092200875
 hello world helld helld helld helld helld helld hel
epoch 69
loss 0.0006446080515161157
 hello world helld helld helld helld helld helld hel
epoch 79
loss 0.00031160045182332397
 hello world helld helld helld helld helld helld hel
epoch 89
loss 0.00016064560622908175
 hello world helld helld helld helld helld helld hel
epoch 99
loss 8.033090125536546e-05
 hello world helld helld helld helld helld helld hel
epoch 109
loss 4.157139119342901e-05
 hello world helld helld helld helld helld helld hel
epoch 119
loss 2.33569426200