In [6]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import matplotlib.pyplot as plt
import pandas as pd
tf.__version__

'1.14.0'

In [7]:
batch_size = 1

def index_to_char(i):
    return chr(i + 97 if (i != 26) else 32)
def char_to_index(ch):
    return ord(ch) - 97 if (ch != ' ') else 26

text = "hello world"
encoding_size = keras.utils.to_categorical(list(set(map(char_to_index, list(text))))).shape[1]

In [8]:
x_train = [[list(keras.utils.to_categorical(list(map(char_to_index, list(" hello world h")))))]] # ' hello'
y_train = [[list(keras.utils.to_categorical(list(map(char_to_index, list("hello world he")))))]] # 'hello '
print(np.array(x_train).shape)
x_train

(1, 1, 14, 27)


[[[array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32),
   array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
   array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
   array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
   array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
   array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32),
   array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
          0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], d

In [9]:
model = keras.Sequential([
    layers.LSTM(20, input_shape=(None, encoding_size), return_sequences=True),
    layers.Dense(encoding_size, activation='softmax')
])

model.compile(
    optimizer=keras.optimizers.RMSprop(learning_rate=0.05),
    loss=keras.losses.categorical_crossentropy
)

def on_epoch_end(epoch, data):
    if epoch % 10 == 9:
        print("epoch", epoch)
        print("loss", data['loss'])
        
        # Generate text from the initial text ' h'
        text = ' h'
        for i in range(50):
            x = [[list(keras.utils.to_categorical(list(map(char_to_index, list(text)))))]]
            y = model.predict(x)[0][-1]
            text += index_to_char(y.argmax())
        print(text)
        
        
model.fit(
    x_train, 
    y_train, 
    batch_size=batch_size, 
    epochs=500, 
    verbose=False,
    callbacks=[keras.callbacks.LambdaCallback(on_epoch_end=on_epoch_end)]
)

epoch 9
loss 0.9973683953285217
 helllll hell hell hell hell hell hell hell hell hel
epoch 19
loss 0.14691917598247528
 hello world hello world hello world hello world hel
epoch 29
loss 0.04025455191731453
 hello world hello world hello world hello world hel
epoch 39
loss 0.017450671643018723
 hello world hello world hello world hello world hel
epoch 49
loss 0.008773858658969402
 hello world hello world hello world hello world hel
epoch 59
loss 0.00464315339922905
 hello world hello world hello world hello world hel
epoch 69
loss 0.002495779888704419
 hello world hello world hello world hello world hel
epoch 79
loss 0.0013922241050750017
 hello world hello world hello world hello world hel
epoch 89
loss 0.0007750742370262742
 hello world hello world hello world hello world hel
epoch 99
loss 0.00043793689110316336
 hello world hello world hello world hello world hel
epoch 109
loss 0.00024882430443540215
 hello world hello world hello world hello world hel
epoch 119
loss 0.00013985008990